<?php
//============================================================+
// File name   : cp_extension.inc                                 
// Begin       : 2001-09-02                                    
// Last Update : 2001-10-27                                    
//                                                             
// Description : This File holds the file extention for 
//               your PHP files and installation URL
//                                                             
// Author: Nicola Asuni                                        
//                                                             
// (c) Copyright:                                              
//               Tecnick.com LTD                            
//               Manor Coach House, Church Hill                          
//               Aldershot, Hants, GU12 4RQ                  
//               UK                                         
//               www.tecnick.com                               
//               info@tecnick.com                              
//============================================================+

// Extension of PHP files
define("CP_EXT","php");

//============================================================+
// END OF FILE                                                 
//============================================================+
?>
